services:
  - type: web
    name: job-portal-backend
    env: node
    buildCommand: ./render-build.sh
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: job-portal-backend
          property: port
    healthCheckPath: /api/health